---
version: "2"
services:
  analytics-collector:
    image: analytics-collector
    build:
      context: ./analytics-collector
      target: dev
    volumes:
      - ./analytics-collector:/usr/src/analytics-collector/
      - nodemodules:/usr/src/analytics-collector/app/node_modules
    ports:
      - "4100:4100"
    environment:
      NODE_ENV: development
      DEBUG: analytics-collector:*
volumes:
  nodemodules: { }